In [20]:
import uproot
import glob
import numpy as np

In [21]:
glob.glob("output/*")

['output/test_Cutflow.cflow',
 'output/manual_postskim_Cutflow.cflow',
 'output/manual_postskim.root']

In [22]:
with uproot.open("output/manual_postskim.root") as root_file:
    rapido_events = root_file.get("tree").get("event").array(library="np")
    
with uproot.open("/ceph/cms/store/user/jguiang/VBSVHSkim/1lep_1ak8_2ak4_postskim/TTTo2L2Nu_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1_NANOAODSIM_1lep_1ak8_2ak4_postskim/output_1.root") as root_file:
    nanoaodtools_events = root_file.get("Events").get("event").array(library="np")

In [23]:
rapido_events

array([ 78633123,  78633813,  78070217, ..., 130052332, 130052388,
       130052757], dtype=int32)

In [24]:
nanoaodtools_events

array([ 78633123,  78633813,  78070217, ..., 130052332, 130052388,
       130052757], dtype=uint64)

In [30]:
rapido_events[~np.isin(rapido_events, nanoaodtools_events)]

array([ 13932472,  47872923, 146988487, 105264637, 130851216,  38593547,
       120579460,  63381761,  13272790,   8154638,  31418562,  19352114,
        79175838,  78707236,  34087498,  41088806,  44095960,  61995283,
        62478226, 100513352, 147427542,  34070105, 107802410,  87087771,
        43347159, 138742686,  68564602,  93919191,  57600460, 118133133,
       113422943, 147588651,  85496954,  52913903, 139297953, 140325884,
        50749288, 130697046], dtype=int32)

In [28]:
nanoaodtools_events[~np.isin(nanoaodtools_events, rapido_events)]

array([130298786,  90477383, 112696064,  37734046,  38305474,  31526393,
        10021439, 118900901,   2941052,  14543714,   1180118,  77619176,
       112044232,  31685067,  53600390, 113255849,  74702852, 115514661,
        11759130, 126632092,  64075356,  65957371,  54161067, 117859068,
       141135518,   9108043, 121872410,  91185720,  17536806,  93731328,
       135946749, 122616630], dtype=uint64)